
import avloniy from '../../assets/imgs/avloniy.png'
import nusrat from '../../assets/imgs/nusrat.png'
import rahmonberdi from '../../assets/imgs/rahmonberdi.png'
import hamza from '../../assets/imgs/hamza.png'
import cholpon from '../../assets/imgs/cholpon.png'
import fitrat from '../../assets/imgs/fitrat.png'
import qodiriy from '../../assets/imgs/qodiriy.png'
import munavvar from '../../assets/imgs/munavvar.png'
import abdulla from '../../assets/imgs/abdulla.png'
import behmudiy from '../../assets/imgs/behmudiy.png'
import hoji from '../../assets/imgs/hoji.png'

import dunyoningishlari from '../../assets/imgs/dunyoningishlari.png'
import ikkieshikorasi from '../../assets/imgs/ikkieshik.png'
import tushda from '../../assets/imgs/tushda.png'
import sophie from '../../assets/imgs/sophie.png'
import littleprince from '../../assets/imgs/littleprince.png'
import candide from '../../assets/imgs/candide.png'

import avloniyAsarlari from '../../assets/imgs/avloniyasari1.jpg'
import nusratAsarlari1 from '../../assets/imgs/nusratasarlari1.jpg'

  let Objects =[
    {
      id:1,
      fname:"AbdullaAvloniy",
      name:"Abdulla Avloniy",
      img:avloniy,
      wasborn:"5-may 1978",
      died:"7-avg 1993",
      birthAddress:"Toshkent, Uzbekistan",
      desc:`XIX asr oxiri XX asr boshidagi ozbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobi Abdulla Avloniydir. U 1878 yilning 12 iyulida Toshkentning Mergancha mahallasida, toquvchi Miravlon aka oilasida dunyoga keldi. Bolaligi Mirobod mahallasining egri-bugri kochalarida, kopchilik qismini ruslar tashkil qilgan temir yol ishchilari bolalari orasida kechdi. Oqchidagi eski maktabda, song madrasada oqidi (1885–1886). Mustaqil mutolaa bilan shugʻullandi. Arab, fors, rus tillarini organdi. Orenburg, Qozon, Tiflisda chiqib turgan gazeta-jurnallarni kuzatib bordi. Qisqa muddat ichida u maʼrifatparvar sifatida tanildi va olkadagi ijgimoiy-madaniy harakatchilikning faol namoyandalaridan biriga aylandi.`,
      worklife:"Yozuvchining ilk asari 1962-yilda „Poʻlat chavandoz“ nomida ocherklar toʻplami tarzida nashrdan chiqdi. Ammo yozuvchiga muvaffaqiyat keltirgan asar 1970-yilda nashr qilingan „Bahor qaytmaydi“ qissasi boʻldi.",
      books:[
        {
          id:20,
          bookname:"Pinak",
          bookpic: avloniyAsarlari,
          ranking:4.1,
          commitnum:865,
          author:"Abdulla Avloniy",
          pages:100,
          published:2001,
          genre:"drama",
          publishing:"nihol nashr",
          moreinfo:"Роман ўтган асрнинг йигирманчи йилларида Германияда таҳсил олган ва собиқ Совет Иттифоқи томонидан шафқатсизларча қатл этилган миллат йигит-қизларининг  хотирасига бағишланади Роман воқеаларини қисқача сўзлар билан ифода этиб бўлмайди. Барчаси шу қадар  тиғизки, шошириб қўяди. Мажоз, образ, ифода, ўт, ҳеч кимникига ўхшамаган лиризмни ҳис қиласиз. Миллият, соф муҳаббат,  кўринмас ва ошкор фожиалар, тарих, бугун ва эртанинг бир-бирига кавшарланган ҳалқаси, ростлик даъвосидаги ёлғонлар, руҳ ва қондаги парадокслар сизни ўтмиш ва келажак куйига асир қилади, ўйлатади, йиғлатади ва аччиқ-аччиқ кулдиради.  Ўтган аср бошида Германияда ўқиган талабалар, улар маслаги ва фожиали қисмати бугунги ёшлар мақсади билан бир тарозига тортилади.",
          paperbook:211,
          audiobook:"3:23",
          elektron:"pdf, epub",
          aboutauthor:"Abdulla Avloniy XIX asr oxiri XX asr boshidagi oʻzbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobidir. U Toshkentning Mergancha mahallasida toʻquvchi Miravlon aka oilasida tavallud topdi. Avval Oʻqchidagi boshlangʻich maktabda, soʻng shahar madrasalaridan birida tahsil oldi. ",
          quote:"Inson bolasi ne kunlarni ko‘rmaydi?!Har bir odam o‘z g‘ami bilan bo‘lsa, hayotdan ko‘z yumib ketganlarga umr bo‘yi motam tutib o‘tsa, bu moddiy olam shu kunlarga yetolarmidi? Hayot to‘lqini ojizlarni qirg‘oqqa irg‘itib tashlaydi. Oqimga qarshi suza olganlar, to‘lqinni egarlaganlargina ertangi kunga yetib keladi.",
          quote2:"Yer kurrasida chumolidek mehnat qilayotganlardan ko‘ra, tuproq tagida yotganlar ko‘p. Yer qatlami odam suyaklariga to‘lib ketgan.",
          rewiev:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
          recommendation:[
              {
                picture:dunyoningishlari,
                title:"Dunyoning ishlari",
                ranking: 2.5,
                comments:200,
              },
              {
                picture:ikkieshikorasi,
                title:"Ikki eshik orasi",
                ranking: 4.3,
                comments:300,
              },
              {
                picture:tushda,
                title:"Tushda kechgan umrlar",
                ranking: 4.5,
                comments:5200,
              },
              {
                picture:sophie,
                title:"To Kill a Mockingbird",
                ranking: 3.9,
                comments:1400,
              },
              {
                picture:littleprince,
                title:"The Little Prince",
                ranking: 4.9,
                comments:300,
              },
              {
                picture:candide,
                title:"Candide",
                ranking: 3.9,
                comments:300,
              },
          ]

        },
        {
          id:200,
          bookname:"Pinak",
          bookpic: avloniyAsarlari,
          ranking:4.1,
          commitnum:865,
          author:"Abdulla Avloniy",
          pages:100,
          published:2001,
          genre:"drama",
          publishing:"nihol nashr",
          moreinfo:"Роман ўтган асрнинг йигирманчи йилларида Германияда таҳсил олган ва собиқ Совет Иттифоқи томонидан шафқатсизларча қатл этилган миллат йигит-қизларининг  хотирасига бағишланади Роман воқеаларини қисқача сўзлар билан ифода этиб бўлмайди. Барчаси шу қадар  тиғизки, шошириб қўяди. Мажоз, образ, ифода, ўт, ҳеч кимникига ўхшамаган лиризмни ҳис қиласиз. Миллият, соф муҳаббат,  кўринмас ва ошкор фожиалар, тарих, бугун ва эртанинг бир-бирига кавшарланган ҳалқаси, ростлик даъвосидаги ёлғонлар, руҳ ва қондаги парадокслар сизни ўтмиш ва келажак куйига асир қилади, ўйлатади, йиғлатади ва аччиқ-аччиқ кулдиради.  Ўтган аср бошида Германияда ўқиган талабалар, улар маслаги ва фожиали қисмати бугунги ёшлар мақсади билан бир тарозига тортилади.",
          paperbook:211,
          audiobook:"3:23",
          elektron:"pdf, epub",
          aboutauthor:"Abdulla Avloniy XIX asr oxiri XX asr boshidagi oʻzbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobidir. U Toshkentning Mergancha mahallasida toʻquvchi Miravlon aka oilasida tavallud topdi. Avval Oʻqchidagi boshlangʻich maktabda, soʻng shahar madrasalaridan birida tahsil oldi. ",
          quote:"Inson bolasi ne kunlarni ko‘rmaydi?!Har bir odam o‘z g‘ami bilan bo‘lsa, hayotdan ko‘z yumib ketganlarga umr bo‘yi motam tutib o‘tsa, bu moddiy olam shu kunlarga yetolarmidi? Hayot to‘lqini ojizlarni qirg‘oqqa irg‘itib tashlaydi. Oqimga qarshi suza olganlar, to‘lqinni egarlaganlargina ertangi kunga yetib keladi.",
          quote2:"Yer kurrasida chumolidek mehnat qilayotganlardan ko‘ra, tuproq tagida yotganlar ko‘p. Yer qatlami odam suyaklariga to‘lib ketgan.",
          rewiev:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
          recommendation:[
              {
                picture:dunyoningishlari,
                title:"Dunyoning ishlari",
                ranking: 2.5,
                comments:200,
              },
              {
                picture:ikkieshikorasi,
                title:"Ikki eshik orasi",
                ranking: 4.3,
                comments:300,
              },
              {
                picture:tushda,
                title:"Tushda kechgan umrlar",
                ranking: 4.5,
                comments:5200,
              },
              {
                picture:sophie,
                title:"To Kill a Mockingbird",
                ranking: 3.9,
                comments:1400,
              },
              {
                picture:littleprince,
                title:"The Little Prince",
                ranking: 4.9,
                comments:300,
              },
              {
                picture:candide,
                title:"Candide",
                ranking: 3.9,
                comments:300,
              },
          ]

        },
        {
          id:201,
          bookname:"Pinak",
          bookpic: avloniyAsarlari,
          ranking:4.1,
          commitnum:865,
          author:"Abdulla Avloniy",
          pages:100,
          published:2001,
          genre:"drama",
          publishing:"nihol nashr",
          moreinfo:"Роман ўтган асрнинг йигирманчи йилларида Германияда таҳсил олган ва собиқ Совет Иттифоқи томонидан шафқатсизларча қатл этилган миллат йигит-қизларининг  хотирасига бағишланади Роман воқеаларини қисқача сўзлар билан ифода этиб бўлмайди. Барчаси шу қадар  тиғизки, шошириб қўяди. Мажоз, образ, ифода, ўт, ҳеч кимникига ўхшамаган лиризмни ҳис қиласиз. Миллият, соф муҳаббат,  кўринмас ва ошкор фожиалар, тарих, бугун ва эртанинг бир-бирига кавшарланган ҳалқаси, ростлик даъвосидаги ёлғонлар, руҳ ва қондаги парадокслар сизни ўтмиш ва келажак куйига асир қилади, ўйлатади, йиғлатади ва аччиқ-аччиқ кулдиради.  Ўтган аср бошида Германияда ўқиган талабалар, улар маслаги ва фожиали қисмати бугунги ёшлар мақсади билан бир тарозига тортилади.",
          paperbook:211,
          audiobook:"3:23",
          elektron:"pdf, epub",
          aboutauthor:"Abdulla Avloniy XIX asr oxiri XX asr boshidagi oʻzbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobidir. U Toshkentning Mergancha mahallasida toʻquvchi Miravlon aka oilasida tavallud topdi. Avval Oʻqchidagi boshlangʻich maktabda, soʻng shahar madrasalaridan birida tahsil oldi. ",
          quote:"Inson bolasi ne kunlarni ko‘rmaydi?!Har bir odam o‘z g‘ami bilan bo‘lsa, hayotdan ko‘z yumib ketganlarga umr bo‘yi motam tutib o‘tsa, bu moddiy olam shu kunlarga yetolarmidi? Hayot to‘lqini ojizlarni qirg‘oqqa irg‘itib tashlaydi. Oqimga qarshi suza olganlar, to‘lqinni egarlaganlargina ertangi kunga yetib keladi.",
          quote2:"Yer kurrasida chumolidek mehnat qilayotganlardan ko‘ra, tuproq tagida yotganlar ko‘p. Yer qatlami odam suyaklariga to‘lib ketgan.",
          rewiev:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
          recommendation:[
              {
                picture:dunyoningishlari,
                title:"Dunyoning ishlari",
                ranking: 2.5,
                comments:200,
              },
              {
                picture:ikkieshikorasi,
                title:"Ikki eshik orasi",
                ranking: 4.3,
                comments:300,
              },
              {
                picture:tushda,
                title:"Tushda kechgan umrlar",
                ranking: 4.5,
                comments:5200,
              },
              {
                picture:sophie,
                title:"To Kill a Mockingbird",
                ranking: 3.9,
                comments:1400,
              },
              {
                picture:littleprince,
                title:"The Little Prince",
                ranking: 4.9,
                comments:300,
              },
              {
                picture:candide,
                title:"Candide",
                ranking: 3.9,
                comments:300,
              },
          ]

        },
        {
          id:202,
          bookname:"Pinak",
          bookpic: avloniyAsarlari,
          ranking:4.1,
          commitnum:865,
          author:"Abdulla Avloniy",
          pages:100,
          published:2001,
          genre:"drama",
          publishing:"nihol nashr",
          moreinfo:"Роман ўтган асрнинг йигирманчи йилларида Германияда таҳсил олган ва собиқ Совет Иттифоқи томонидан шафқатсизларча қатл этилган миллат йигит-қизларининг  хотирасига бағишланади Роман воқеаларини қисқача сўзлар билан ифода этиб бўлмайди. Барчаси шу қадар  тиғизки, шошириб қўяди. Мажоз, образ, ифода, ўт, ҳеч кимникига ўхшамаган лиризмни ҳис қиласиз. Миллият, соф муҳаббат,  кўринмас ва ошкор фожиалар, тарих, бугун ва эртанинг бир-бирига кавшарланган ҳалқаси, ростлик даъвосидаги ёлғонлар, руҳ ва қондаги парадокслар сизни ўтмиш ва келажак куйига асир қилади, ўйлатади, йиғлатади ва аччиқ-аччиқ кулдиради.  Ўтган аср бошида Германияда ўқиган талабалар, улар маслаги ва фожиали қисмати бугунги ёшлар мақсади билан бир тарозига тортилади.",
          paperbook:211,
          audiobook:"3:23",
          elektron:"pdf, epub",
          aboutauthor:"Abdulla Avloniy XIX asr oxiri XX asr boshidagi oʻzbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobidir. U Toshkentning Mergancha mahallasida toʻquvchi Miravlon aka oilasida tavallud topdi. Avval Oʻqchidagi boshlangʻich maktabda, soʻng shahar madrasalaridan birida tahsil oldi. ",
          quote:"Inson bolasi ne kunlarni ko‘rmaydi?!Har bir odam o‘z g‘ami bilan bo‘lsa, hayotdan ko‘z yumib ketganlarga umr bo‘yi motam tutib o‘tsa, bu moddiy olam shu kunlarga yetolarmidi? Hayot to‘lqini ojizlarni qirg‘oqqa irg‘itib tashlaydi. Oqimga qarshi suza olganlar, to‘lqinni egarlaganlargina ertangi kunga yetib keladi.",
          quote2:"Yer kurrasida chumolidek mehnat qilayotganlardan ko‘ra, tuproq tagida yotganlar ko‘p. Yer qatlami odam suyaklariga to‘lib ketgan.",
          rewiev:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
          recommendation:[
              {
                picture:dunyoningishlari,
                title:"Dunyoning ishlari",
                ranking: 2.5,
                comments:200,
              },
              {
                picture:ikkieshikorasi,
                title:"Ikki eshik orasi",
                ranking: 4.3,
                comments:300,
              },
              {
                picture:tushda,
                title:"Tushda kechgan umrlar",
                ranking: 4.5,
                comments:5200,
              },
              {
                picture:sophie,
                title:"To Kill a Mockingbird",
                ranking: 3.9,
                comments:1400,
              },
              {
                picture:littleprince,
                title:"The Little Prince",
                ranking: 4.9,
                comments:300,
              },
              {
                picture:candide,
                title:"Candide",
                ranking: 3.9,
                comments:300,
              },
          ]

        },
      ],
    },
    {
      id:2,
      fname:"Nusrat",
      name:"Nusrat Rahmat",
      img:nusrat,
      wasborn:"5-may 1941",
      died:"7-avg 2017",
      birthAddress:"Toshkent, Uzbekistan",
      desc:`XIX asr oxiri XX asr boshidagi ozbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobi Abdulla Avloniydir. U 1878 yilning 12 iyulida Toshkentning Mergancha aa bilan shugʻullandi. Arab, fors, rus tillarini organdi. Orenburg, Qozon, Tiflisda chiqib turgan gazeta-jurnallarni kuzatib bordi. Qisqa muddat ichida u maʼrifatparvar sifatida tanildi va olkadagi ijgimoiy-madaniy harakatchilikning faol namoyandalaridan biriga aylandi.`,
      worklife:"Yozuvchining ilk asari 1962-yilda „Poʻlat chavandoz“ nomida ocherklar toʻplami tarzida nashrdan chiqdi. Ammo yozuvchiga muvaffaqiyat keltirgan asar 1970-yilda nashr qilingan „Bahor qaytmaydi“ qissasi boʻldi.",
      books:[
        // {
        //   id:24,
        //   bookname:"Pinaklll",
        //   bookpic:nusratAsarlari1,
        //   ranking:3.3,
        //   commitnum:60,
        //   pages:300,
        //   published:2001,
        //   genre:"drama",
        //   publishing:"nihol nashr",
        // },
        {
          id:24,
          bookname:"Freezing Order",
          bookpic: "https://images.booksense.com/images/281/153/9781982153281.jpg",
          ranking:4.1,
          commitnum:865,
          author:"Nusrat Rahmat",
          pages:100,
          published:2001,
          genre:"drama",
          publishing:"nihol nashr",
          moreinfo:"Роман ўтган асрнинг йигирманчи йилларида Германияда таҳсил олган ва собиқ Совет Иттифоқи томонидан шафқатсизларча қатл этилган миллат йигит-қизларининг  хотирасига бағишланади Роман воқеаларини қисқача сўзлар билан ифода этиб бўлмайди. Барчаси шу қадар  тиғизки, шошириб қўяди. Мажоз, образ, ифода, ўт, ҳеч кимникига ўхшамаган лиризмни ҳис қиласиз. Миллият, соф муҳаббат,  кўринмас ва ошкор фожиалар, тарих, бугун ва эртанинг бир-бирига кавшарланган ҳалқаси, ростлик даъвосидаги ёлғонлар, руҳ ва қондаги парадокслар сизни ўтмиш ва келажак куйига асир қилади, ўйлатади, йиғлатади ва аччиқ-аччиқ кулдиради.  Ўтган аср бошида Германияда ўқиган талабалар, улар маслаги ва фожиали қисмати бугунги ёшлар мақсади билан бир тарозига тортилади.",
          paperbook:211,
          audiobook:"3:23",
          elektron:"pdf, epub",
          aboutauthor:"Abdulla Avloniy XIX asr oxiri XX asr boshidagi oʻzbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobidir. U Toshkentning Mergancha mahallasida toʻquvchi Miravlon aka oilasida tavallud topdi. Avval Oʻqchidagi boshlangʻich maktabda, soʻng shahar madrasalaridan birida tahsil oldi. ",
          quote:"Inson bolasi ne kunlarni ko‘rmaydi?!Har bir odam o‘z g‘ami bilan bo‘lsa, hayotdan ko‘z yumib ketganlarga umr bo‘yi motam tutib o‘tsa, bu moddiy olam shu kunlarga yetolarmidi? Hayot to‘lqini ojizlarni qirg‘oqqa irg‘itib tashlaydi. Oqimga qarshi suza olganlar, to‘lqinni egarlaganlargina ertangi kunga yetib keladi.",
          quote2:"Yer kurrasida chumolidek mehnat qilayotganlardan ko‘ra, tuproq tagida yotganlar ko‘p. Yer qatlami odam suyaklariga to‘lib ketgan.",
          rewiev:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
          recommendation:[
            {
              picture:dunyoningishlari,
              title:"Dunyoning ishlari",
              ranking: 2.5,
              comments:200,
            },
            {
              picture:ikkieshikorasi,
              title:"Ikki eshik orasi",
              ranking: 4.3,
              comments:300,
            },
            {
              picture:tushda,
              title:"Tushda kechgan umrlar",
              ranking: 4.5,
              comments:5200,
            },
            {
              picture:sophie,
              title:"To Kill a Mockingbird",
              ranking: 3.9,
              comments:1400,
            },
            {
              picture:littleprince,
              title:"The Little Prince",
              ranking: 4.9,
              comments:300,
            },
            {
              picture:candide,
              title:"Candide",
              ranking: 3.9,
              comments:300,
            },
          ]

        },
      ],
    },
    {
      id:3,
      fname:"Rahmonberdi",
      name:"Rahmonberdi Madazimov",
      img:rahmonberdi,
      wasborn:"5-may 1975",
      died:"7-avg 1933",
      birthAddress:"Toshkent, Uzbekistan",
      desc:`XIX asr oxiri XX asr boshidagi ozbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobi Abdulla Avloniydir. U 1878 yilning 12 iyulida Toshkentning Mergancha mahallasida, toquvchi Miravlon aka oilasida dunyoga keldi. Bolaligi Mirobod mahallifatparvar sifatida tanildi va olkadagi ijgimoiy-madaniy harakatchilikning faol namoyandalaridan biriga aylandi.`,
      worklife:"Yozuvchining ilk asari 1962-yilda „Poʻlat chavandoz“ nomida ocherklar toʻplami tarzida nashrdan chiqdi. Ammo yozuvchiga muvaffaqiyat keltirgan asar 1970-yilda nashr qilingan „Bahor qaytmaydi“ qissasi boʻldi.",
      books:[
        // {
        //   id:25,
        //   bookname:"Pinak",
        //   bookpic:"https://saviya.uz/wp-content/uploads/2017/04/abdulla_avloniy-640x400.jpg?x94708",
        //   ranking:3.1,
        //   commitnum:120,
        //   pages:300,
        //   published:2001,
        //   genre:"drama",
        //   publishing:"nihol nashr",
        // },
        {
          id:25,
          bookname:"Spooki",
          bookpic: "https://rowman.com/L/14/930/9781493044894.jpg",
          ranking:4.1,
          commitnum:865,
          author:"Rahmonberdi Madazimov",
          pages:100,
          published:2001,
          genre:"drama",
          publishing:"nihol nashr",
          moreinfo:"Роман ўтган асрнинг йигирманчи йилларида Германияда таҳсил олган ва собиқ Совет Иттифоқи томонидан шафқатсизларча қатл этилган миллат йигит-қизларининг  хотирасига бағишланади Роман воқеаларини қисқача сўзлар билан ифода этиб бўлмайди. Барчаси шу қадар  тиғизки, шошириб қўяди. Мажоз, образ, ифода, ўт, ҳеч кимникига ўхшамаган лиризмни ҳис қиласиз. Миллият, соф муҳаббат,  кўринмас ва ошкор фожиалар, тарих, бугун ва эртанинг бир-бирига кавшарланган ҳалқаси, ростлик даъвосидаги ёлғонлар, руҳ ва қондаги парадокслар сизни ўтмиш ва келажак куйига асир қилади, ўйлатади, йиғлатади ва аччиқ-аччиқ кулдиради.  Ўтган аср бошида Германияда ўқиган талабалар, улар маслаги ва фожиали қисмати бугунги ёшлар мақсади билан бир тарозига тортилади.",
          paperbook:211,
          audiobook:"3:23",
          elektron:"pdf, epub",
          aboutauthor:"Abdulla Avloniy XIX asr oxiri XX asr boshidagi oʻzbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobidir. U Toshkentning Mergancha mahallasida toʻquvchi Miravlon aka oilasida tavallud topdi. Avval Oʻqchidagi boshlangʻich maktabda, soʻng shahar madrasalaridan birida tahsil oldi. ",
          quote:"Inson bolasi ne kunlarni ko‘rmaydi?!Har bir odam o‘z g‘ami bilan bo‘lsa, hayotdan ko‘z yumib ketganlarga umr bo‘yi motam tutib o‘tsa, bu moddiy olam shu kunlarga yetolarmidi? Hayot to‘lqini ojizlarni qirg‘oqqa irg‘itib tashlaydi. Oqimga qarshi suza olganlar, to‘lqinni egarlaganlargina ertangi kunga yetib keladi.",
          quote2:"Yer kurrasida chumolidek mehnat qilayotganlardan ko‘ra, tuproq tagida yotganlar ko‘p. Yer qatlami odam suyaklariga to‘lib ketgan.",
          rewiev:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
          recommendation:[
            {
              picture:dunyoningishlari,
              title:"Dunyoning ishlari",
              ranking: 2.5,
              comments:200,
            },
            {
              picture:ikkieshikorasi,
              title:"Ikki eshik orasi",
              ranking: 4.3,
              comments:300,
            },
            {
              picture:tushda,
              title:"Tushda kechgan umrlar",
              ranking: 4.5,
              comments:5200,
            },
            {
              picture:sophie,
              title:"To Kill a Mockingbird",
              ranking: 3.9,
              comments:1400,
            },
            {
              picture:littleprince,
              title:"The Little Prince",
              ranking: 4.9,
              comments:300,
            },
            {
              picture:candide,
              title:"Candide",
              ranking: 3.9,
              comments:300,
            },
          ]

        },
      ],
    },
    {
      id:4,
      fname:"Hamza",
      name:"Hamza Hakimzoda Niyoziy",
      img:hamza,
      wasborn:"5-may 1889",
      died:"7-avg 1929",
      birthAddress:"Toshkent, Uzbekistan",
      desc:`XIX asr oxiri XX asr boshidagi ozbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobi Abdulla Avloniydir. U 1878 yilning 12 iyulida Toshkentning Mergancha mahallasida, toquvchi Miravlon aka oilasida dunyoga keldi. Bolaligi Mirobod mahallifatparvar sifatida tanildi va olkadagi ijgimoiy-madaniy harakatchilikning faol namoyandalaridan biriga aylandi.`,
      worklife:"Yozuvchining ilk asari 1962-yilda „Poʻlat chavandoz“ nomida ocherklar toʻplami tarzida nashrdan chiqdi. Ammo yozuvchiga muvaffaqiyat keltirgan asar 1970-yilda nashr qilingan „Bahor qaytmaydi“ qissasi boʻldi.",
      books:[
        // {
        //   id:26,
        //   bookname:"Pinak",
        //   bookpic:"https://saviya.uz/wp-content/uploads/2017/04/abdulla_avloniy-640x400.jpg?x94708",
        //   ranking:3.3,
        //   commitnum:60,
        //   pages:300,
        //   published:2001,
        //   genre:"drama",
        //   publishing:"nihol nashr",
        // },
        {
          id:26,
          bookname:"The Guide",
          bookpic: "https://images.booksense.com/images/968/898/9781984898968.jpg",
          ranking:4.1,
          commitnum:865,
          author:"Hamza Hakimzoda Niyoziy",
          pages:100,
          published:2001,
          genre:"drama",
          publishing:"nihol nashr",
          moreinfo:"Роман ўтган асрнинг йигирманчи йилларида Германияда таҳсил олган ва собиқ Совет Иттифоқи томонидан шафқатсизларча қатл этилган миллат йигит-қизларининг  хотирасига бағишланади Роман воқеаларини қисқача сўзлар билан ифода этиб бўлмайди. Барчаси шу қадар  тиғизки, шошириб қўяди. Мажоз, образ, ифода, ўт, ҳеч кимникига ўхшамаган лиризмни ҳис қиласиз. Миллият, соф муҳаббат,  кўринмас ва ошкор фожиалар, тарих, бугун ва эртанинг бир-бирига кавшарланган ҳалқаси, ростлик даъвосидаги ёлғонлар, руҳ ва қондаги парадокслар сизни ўтмиш ва келажак куйига асир қилади, ўйлатади, йиғлатади ва аччиқ-аччиқ кулдиради.  Ўтган аср бошида Германияда ўқиган талабалар, улар маслаги ва фожиали қисмати бугунги ёшлар мақсади билан бир тарозига тортилади.",
          paperbook:211,
          audiobook:"3:23",
          elektron:"pdf, epub",
          aboutauthor:"Abdulla Avloniy XIX asr oxiri XX asr boshidagi oʻzbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobidir. U Toshkentning Mergancha mahallasida toʻquvchi Miravlon aka oilasida tavallud topdi. Avval Oʻqchidagi boshlangʻich maktabda, soʻng shahar madrasalaridan birida tahsil oldi. ",
          quote:"Inson bolasi ne kunlarni ko‘rmaydi?!Har bir odam o‘z g‘ami bilan bo‘lsa, hayotdan ko‘z yumib ketganlarga umr bo‘yi motam tutib o‘tsa, bu moddiy olam shu kunlarga yetolarmidi? Hayot to‘lqini ojizlarni qirg‘oqqa irg‘itib tashlaydi. Oqimga qarshi suza olganlar, to‘lqinni egarlaganlargina ertangi kunga yetib keladi.",
          quote2:"Yer kurrasida chumolidek mehnat qilayotganlardan ko‘ra, tuproq tagida yotganlar ko‘p. Yer qatlami odam suyaklariga to‘lib ketgan.",
          rewiev:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
          recommendation:[
            {
              picture:dunyoningishlari,
              title:"Dunyoning ishlari",
              ranking: 2.5,
              comments:200,
            },
            {
              picture:ikkieshikorasi,
              title:"Ikki eshik orasi",
              ranking: 4.3,
              comments:300,
            },
            {
              picture:tushda,
              title:"Tushda kechgan umrlar",
              ranking: 4.5,
              comments:5200,
            },
            {
              picture:sophie,
              title:"To Kill a Mockingbird",
              ranking: 3.9,
              comments:1400,
            },
            {
              picture:littleprince,
              title:"The Little Prince",
              ranking: 4.9,
              comments:300,
            },
            {
              picture:candide,
              title:"Candide",
              ranking: 3.9,
              comments:300,
            },
          ]

        },
        
      ],
    },
    {
      id:5,
      fname:"Abdulhamid",
      name:"Abdulhamid Cho'lpon",
      img:cholpon,
      wasborn:"5-may 1897",
      died:"7-avg 1938",
      birthAddress:"Toshkent, Uzbekistan",
      desc:`XIX asr oxiri XX asr boshidagi ozbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobi Abdulla Avloniydir. U 1878 yilning 12 iyulida Toshkentning Mergancha mahallasida, toquvchi Miravlon aka oilasida dunyoga keldi. Bolaligi Mirobod mahallifatparvar sifatida tanildi va olkadagi ijgimoiy-madaniy harakatchilikning faol namoyandalaridan biriga aylandi.`,
      worklife:"Yozuvchining ilk asari 1962-yilda „Poʻlat chavandoz“ nomida ocherklar toʻplami tarzida nashrdan chiqdi. Ammo yozuvchiga muvaffaqiyat keltirgan asar 1970-yilda nashr qilingan „Bahor qaytmaydi“ qissasi boʻldi.",
      books:[
        // {
        //   id:27,
        //   bookname:"Pinak",
        //   bookpic:"https://saviya.uz/wp-content/uploads/2017/04/abdulla_avloniy-640x400.jpg?x94708",
        //   ranking:3.3,
        //   commitnum:60,
        //   pages:300,
        //   published:2001,
        //   genre:"drama",
        //   publishing:"nihol nashr",
        // },
        {
          id:27,
          bookname:"System",
          bookpic: "https://media.vanityfair.com/photos/627d2e760a29d0182d5876c5/master/w_2560%2Cc_limit/9780571363780%2520(2)%2520(1).jpg",
          ranking:4.1,
          commitnum:865,
          author:"Abdulhamid Cho'lpon",
          pages:100,
          published:2001,
          genre:"drama",
          publishing:"nihol nashr",
          moreinfo:"Роман ўтган асрнинг йигирманчи йилларида Германияда таҳсил олган ва собиқ Совет Иттифоқи томонидан шафқатсизларча қатл этилган миллат йигит-қизларининг  хотирасига бағишланади Роман воқеаларини қисқача сўзлар билан ифода этиб бўлмайди. Барчаси шу қадар  тиғизки, шошириб қўяди. Мажоз, образ, ифода, ўт, ҳеч кимникига ўхшамаган лиризмни ҳис қиласиз. Миллият, соф муҳаббат,  кўринмас ва ошкор фожиалар, тарих, бугун ва эртанинг бир-бирига кавшарланган ҳалқаси, ростлик даъвосидаги ёлғонлар, руҳ ва қондаги парадокслар сизни ўтмиш ва келажак куйига асир қилади, ўйлатади, йиғлатади ва аччиқ-аччиқ кулдиради.  Ўтган аср бошида Германияда ўқиган талабалар, улар маслаги ва фожиали қисмати бугунги ёшлар мақсади билан бир тарозига тортилади.",
          paperbook:211,
          audiobook:"3:23",
          elektron:"pdf, epub",
          aboutauthor:"Abdulla Avloniy XIX asr oxiri XX asr boshidagi oʻzbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobidir. U Toshkentning Mergancha mahallasida toʻquvchi Miravlon aka oilasida tavallud topdi. Avval Oʻqchidagi boshlangʻich maktabda, soʻng shahar madrasalaridan birida tahsil oldi. ",
          quote:"Inson bolasi ne kunlarni ko‘rmaydi?!Har bir odam o‘z g‘ami bilan bo‘lsa, hayotdan ko‘z yumib ketganlarga umr bo‘yi motam tutib o‘tsa, bu moddiy olam shu kunlarga yetolarmidi? Hayot to‘lqini ojizlarni qirg‘oqqa irg‘itib tashlaydi. Oqimga qarshi suza olganlar, to‘lqinni egarlaganlargina ertangi kunga yetib keladi.",
          quote2:"Yer kurrasida chumolidek mehnat qilayotganlardan ko‘ra, tuproq tagida yotganlar ko‘p. Yer qatlami odam suyaklariga to‘lib ketgan.",
          rewiev:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
          recommendation:[
            {
              picture:dunyoningishlari,
              title:"Dunyoning ishlari",
              ranking: 2.5,
              comments:200,
            },
            {
              picture:ikkieshikorasi,
              title:"Ikki eshik orasi",
              ranking: 4.3,
              comments:300,
            },
            {
              picture:tushda,
              title:"Tushda kechgan umrlar",
              ranking: 4.5,
              comments:5200,
            },
            {
              picture:sophie,
              title:"To Kill a Mockingbird",
              ranking: 3.9,
              comments:1400,
            },
            {
              picture:littleprince,
              title:"The Little Prince",
              ranking: 4.9,
              comments:300,
            },
            {
              picture:candide,
              title:"Candide",
              ranking: 3.9,
              comments:300,
            },
          ]

        },
      ],
    },
    {
      id:6,
      fname:"Abdurauf",
      name:"Abdurauf Fitrat",
      img:fitrat,
      wasborn:"5-may 1886",
      died:"7-avg 1938",
      birthAddress:"Toshkent, Uzbekistan",
      desc:`XIX asr oxiri XX asr boshidagi ozbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobi Abdulla Avloniydir. U 1878 yilning 12 iyulida Toshkentning Mergancha mahallasida, toquvchi Miravlon aka oilasida dunyoga keldi. Bolaligi Mirobod mahallifatparvar sifatida tanildi va olkadagi ijgimoiy-madaniy harakatchilikning faol namoyandalaridan biriga aylandi.`,
      worklife:"Yozuvchining ilk asari 1962-yilda „Poʻlat chavandoz“ nomida ocherklar toʻplami tarzida nashrdan chiqdi. Ammo yozuvchiga muvaffaqiyat keltirgan asar 1970-yilda nashr qilingan „Bahor qaytmaydi“ qissasi boʻldi.",
      books:[
        // {
        //   id:28,
        //   bookname:"Pinak",
        //   bookpic:"https://saviya.uz/wp-content/uploads/2017/04/abdulla_avloniy-640x400.jpg?x94708",
        //   ranking:3.3,
        //   commitnum:60,
        //   pages:300,
        //   published:2001,
        //   genre:"drama",
        //   publishing:"nihol nashr",
        // },
        {
          id:28,
          bookname:"JavaScript",
          bookpic: "https://eloquentjavascript.net/img/cover.jpg",
          ranking:4.1,
          commitnum:865,
          author:"Abdurauf Fitrat",
          pages:100,
          published:2001,
          genre:"drama",
          publishing:"nihol nashr",
          moreinfo:"Роман ўтган асрнинг йигирманчи йилларида Германияда таҳсил олган ва собиқ Совет Иттифоқи томонидан шафқатсизларча қатл этилган миллат йигит-қизларининг  хотирасига бағишланади Роман воқеаларини қисқача сўзлар билан ифода этиб бўлмайди. Барчаси шу қадар  тиғизки, шошириб қўяди. Мажоз, образ, ифода, ўт, ҳеч кимникига ўхшамаган лиризмни ҳис қиласиз. Миллият, соф муҳаббат,  кўринмас ва ошкор фожиалар, тарих, бугун ва эртанинг бир-бирига кавшарланган ҳалқаси, ростлик даъвосидаги ёлғонлар, руҳ ва қондаги парадокслар сизни ўтмиш ва келажак куйига асир қилади, ўйлатади, йиғлатади ва аччиқ-аччиқ кулдиради.  Ўтган аср бошида Германияда ўқиган талабалар, улар маслаги ва фожиали қисмати бугунги ёшлар мақсади билан бир тарозига тортилади.",
          paperbook:211,
          audiobook:"3:23",
          elektron:"pdf, epub",
          aboutauthor:"Abdulla Avloniy XIX asr oxiri XX asr boshidagi oʻzbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobidir. U Toshkentning Mergancha mahallasida toʻquvchi Miravlon aka oilasida tavallud topdi. Avval Oʻqchidagi boshlangʻich maktabda, soʻng shahar madrasalaridan birida tahsil oldi. ",
          quote:"Inson bolasi ne kunlarni ko‘rmaydi?!Har bir odam o‘z g‘ami bilan bo‘lsa, hayotdan ko‘z yumib ketganlarga umr bo‘yi motam tutib o‘tsa, bu moddiy olam shu kunlarga yetolarmidi? Hayot to‘lqini ojizlarni qirg‘oqqa irg‘itib tashlaydi. Oqimga qarshi suza olganlar, to‘lqinni egarlaganlargina ertangi kunga yetib keladi.",
          quote2:"Yer kurrasida chumolidek mehnat qilayotganlardan ko‘ra, tuproq tagida yotganlar ko‘p. Yer qatlami odam suyaklariga to‘lib ketgan.",
          rewiev:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
          recommendation:[
            {
              picture:dunyoningishlari,
              title:"Dunyoning ishlari",
              ranking: 2.5,
              comments:200,
            },
            {
              picture:ikkieshikorasi,
              title:"Ikki eshik orasi",
              ranking: 4.3,
              comments:300,
            },
            {
              picture:tushda,
              title:"Tushda kechgan umrlar",
              ranking: 4.5,
              comments:5200,
            },
            {
              picture:sophie,
              title:"To Kill a Mockingbird",
              ranking: 3.9,
              comments:1400,
            },
            {
              picture:littleprince,
              title:"The Little Prince",
              ranking: 4.9,
              comments:300,
            },
            {
              picture:candide,
              title:"Candide",
              ranking: 3.9,
              comments:300,
            },
          ]

        },
      ],
    },
    {
      id:7,
      fname:"Abdulmajid",
      name:"Abdulmajid Qodiriy",
      img:qodiriy,
      wasborn:"5-may 1880",
      died:"7-avg 1938",
      birthAddress:"Toshkent, Uzbekistan",
      desc:`XIX asr oxiri XX asr boshidagi ozbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobi Abdulla Avloniydir. U 1878 yilning 12 iyulida Toshkentning Mergancha mahallasida, toquvchi Miravlon aka oilasida dunyoga keldi. Bolaligi Mirobod mahallifatparvar sifatida tanildi va olkadagi ijgimoiy-madaniy harakatchilikning faol namoyandalaridan biriga aylandi.`,
      worklife:"Yozuvchining ilk asari 1962-yilda „Poʻlat chavandoz“ nomida ocherklar toʻplami tarzida nashrdan chiqdi. Ammo yozuvchiga muvaffaqiyat keltirgan asar 1970-yilda nashr qilingan „Bahor qaytmaydi“ qissasi boʻldi.",
      books:[
        // {
        //   id:29,
        //   bookname:"Pinak",
        //   bookpic:"https://saviya.uz/wp-content/uploads/2017/04/abdulla_avloniy-640x400.jpg?x94708",
        //   ranking:3.3,
        //   commitnum:60,
        //   pages:300,
        //   published:2001,
        //   genre:"drama",
        //   publishing:"nihol nashr",
        // },
        {
          id:29,
          bookname:"Edit this book cover",
          bookpic: "https://edit.org/photos/img/blog/t9i-edit-book-covers-online.jpg-840.jpg",
          ranking:4.1,
          commitnum:865,
          author:"Abdulmajid Qodiriy",
          pages:100,
          published:2001,
          genre:"drama",
          publishing:"nihol nashr",
          moreinfo:"Роман ўтган асрнинг йигирманчи йилларида Германияда таҳсил олган ва собиқ Совет Иттифоқи томонидан шафқатсизларча қатл этилган миллат йигит-қизларининг  хотирасига бағишланади Роман воқеаларини қисқача сўзлар билан ифода этиб бўлмайди. Барчаси шу қадар  тиғизки, шошириб қўяди. Мажоз, образ, ифода, ўт, ҳеч кимникига ўхшамаган лиризмни ҳис қиласиз. Миллият, соф муҳаббат,  кўринмас ва ошкор фожиалар, тарих, бугун ва эртанинг бир-бирига кавшарланган ҳалқаси, ростлик даъвосидаги ёлғонлар, руҳ ва қондаги парадокслар сизни ўтмиш ва келажак куйига асир қилади, ўйлатади, йиғлатади ва аччиқ-аччиқ кулдиради.  Ўтган аср бошида Германияда ўқиган талабалар, улар маслаги ва фожиали қисмати бугунги ёшлар мақсади билан бир тарозига тортилади.",
          paperbook:211,
          audiobook:"3:23",
          elektron:"pdf, epub",
          aboutauthor:"Abdulla Avloniy XIX asr oxiri XX asr boshidagi oʻzbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobidir. U Toshkentning Mergancha mahallasida toʻquvchi Miravlon aka oilasida tavallud topdi. Avval Oʻqchidagi boshlangʻich maktabda, soʻng shahar madrasalaridan birida tahsil oldi. ",
          quote:"Inson bolasi ne kunlarni ko‘rmaydi?!Har bir odam o‘z g‘ami bilan bo‘lsa, hayotdan ko‘z yumib ketganlarga umr bo‘yi motam tutib o‘tsa, bu moddiy olam shu kunlarga yetolarmidi? Hayot to‘lqini ojizlarni qirg‘oqqa irg‘itib tashlaydi. Oqimga qarshi suza olganlar, to‘lqinni egarlaganlargina ertangi kunga yetib keladi.",
          quote2:"Yer kurrasida chumolidek mehnat qilayotganlardan ko‘ra, tuproq tagida yotganlar ko‘p. Yer qatlami odam suyaklariga to‘lib ketgan.",
          rewiev:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
          recommendation:[
            {
              picture:dunyoningishlari,
              title:"Dunyoning ishlari",
              ranking: 2.5,
              comments:200,
            },
            {
              picture:ikkieshikorasi,
              title:"Ikki eshik orasi",
              ranking: 4.3,
              comments:300,
            },
            {
              picture:tushda,
              title:"Tushda kechgan umrlar",
              ranking: 4.5,
              comments:5200,
            },
            {
              picture:sophie,
              title:"To Kill a Mockingbird",
              ranking: 3.9,
              comments:1400,
            },
            {
              picture:littleprince,
              title:"The Little Prince",
              ranking: 4.9,
              comments:300,
            },
            {
              picture:candide,
              title:"Candide",
              ranking: 3.9,
              comments:300,
            },
          ]

        },
      ],
    },
    {
      id:8,
      fname:"Munavvarqori",
      name:"Munavvarqori Abdurashidxonov",
      img:munavvar,
      wasborn:"5-may 1878",
      died:"7-avg 1931",
      birthAddress:"Toshkent, Uzbekistan",
      desc:`XIX asr oxiri XX asr boshidagi ozbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobi Abdulla Avloniydir. U 1878 yilning 12 iyulida Toshkentning Mergancha mahallasida, toquvchi Miravlon aka oilasida dunyoga keldi. Bolaligi Mirobod mahallifatparvar sifatida tanildi va olkadagi ijgimoiy-madaniy harakatchilikning faol namoyandalaridan biriga aylandi.`,
      worklife:"Yozuvchining ilk asari 1962-yilda „Poʻlat chavandoz“ nomida ocherklar toʻplami tarzida nashrdan chiqdi. Ammo yozuvchiga muvaffaqiyat keltirgan asar 1970-yilda nashr qilingan „Bahor qaytmaydi“ qissasi boʻldi.",
      books:[
        // {
        //   id:30,
        //   bookname:"Pinak",
        //   bookpic:"https://saviya.uz/wp-content/uploads/2017/04/abdulla_avloniy-640x400.jpg?x94708",
        //   ranking:3.3,
        //   commitnum:60,
        //   pages:300,
        //   published:2001,
        //   genre:"drama",
        //   publishing:"nihol nashr",
        // },
        {
          id:30,
          bookname:"Sooley",
          bookpic: "https://img1.od-cdn.com/ImageType-100/0111-1/%7B396CF4B5-53C4-47E2-B545-B9CA756E2CCC%7DImg100.jpg",
          ranking:4.1,
          commitnum:865,
          author:"Munavvarqori Abdurashidxonov",
          pages:100,
          published:2001,
          genre:"drama",
          publishing:"nihol nashr",
          moreinfo:"Роман ўтган асрнинг йигирманчи йилларида Германияда таҳсил олган ва собиқ Совет Иттифоқи томонидан шафқатсизларча қатл этилган миллат йигит-қизларининг  хотирасига бағишланади Роман воқеаларини қисқача сўзлар билан ифода этиб бўлмайди. Барчаси шу қадар  тиғизки, шошириб қўяди. Мажоз, образ, ифода, ўт, ҳеч кимникига ўхшамаган лиризмни ҳис қиласиз. Миллият, соф муҳаббат,  кўринмас ва ошкор фожиалар, тарих, бугун ва эртанинг бир-бирига кавшарланган ҳалқаси, ростлик даъвосидаги ёлғонлар, руҳ ва қондаги парадокслар сизни ўтмиш ва келажак куйига асир қилади, ўйлатади, йиғлатади ва аччиқ-аччиқ кулдиради.  Ўтган аср бошида Германияда ўқиган талабалар, улар маслаги ва фожиали қисмати бугунги ёшлар мақсади билан бир тарозига тортилади.",
          paperbook:211,
          audiobook:"3:23",
          elektron:"pdf, epub",
          aboutauthor:"Abdulla Avloniy XIX asr oxiri XX asr boshidagi oʻzbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobidir. U Toshkentning Mergancha mahallasida toʻquvchi Miravlon aka oilasida tavallud topdi. Avval Oʻqchidagi boshlangʻich maktabda, soʻng shahar madrasalaridan birida tahsil oldi. ",
          quote:"Inson bolasi ne kunlarni ko‘rmaydi?!Har bir odam o‘z g‘ami bilan bo‘lsa, hayotdan ko‘z yumib ketganlarga umr bo‘yi motam tutib o‘tsa, bu moddiy olam shu kunlarga yetolarmidi? Hayot to‘lqini ojizlarni qirg‘oqqa irg‘itib tashlaydi. Oqimga qarshi suza olganlar, to‘lqinni egarlaganlargina ertangi kunga yetib keladi.",
          quote2:"Yer kurrasida chumolidek mehnat qilayotganlardan ko‘ra, tuproq tagida yotganlar ko‘p. Yer qatlami odam suyaklariga to‘lib ketgan.",
          rewiev:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
          recommendation:[
            {
              picture:dunyoningishlari,
              title:"Dunyoning ishlari",
              ranking: 2.5,
              comments:200,
            },
            {
              picture:ikkieshikorasi,
              title:"Ikki eshik orasi",
              ranking: 4.3,
              comments:300,
            },
            {
              picture:tushda,
              title:"Tushda kechgan umrlar",
              ranking: 4.5,
              comments:5200,
            },
            {
              picture:sophie,
              title:"To Kill a Mockingbird",
              ranking: 3.9,
              comments:1400,
            },
            {
              picture:littleprince,
              title:"The Little Prince",
              ranking: 4.9,
              comments:300,
            },
            {
              picture:candide,
              title:"Candide",
              ranking: 3.9,
              comments:300,
            },
          ]

        },
      ],
    },
    {
      id:9,
      fname:"Abdulla",
      name:"Abdulla Qodiriy",
      img:abdulla,
      wasborn:"5-may 1894",
      died:"7-avg 1938",
      birthAddress:"Toshkent, Uzbekistan",
      desc:`XIX asr oxiri XX asr boshidagi ozbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobi Abdulla Avloniydir. U 1878 yilning 12 iyulida Toshkentning Mergancha mahallasida, toquvchi Miravlon aka oilasida dunyoga keldi. Bolaligi Mirobod mahallifatparvar sifatida tanildi va olkadagi ijgimoiy-madaniy harakatchilikning faol namoyandalaridan biriga aylandi.`,
      worklife:"Yozuvchining ilk asari 1962-yilda „Poʻlat chavandoz“ nomida ocherklar toʻplami tarzida nashrdan chiqdi. Ammo yozuvchiga muvaffaqiyat keltirgan asar 1970-yilda nashr qilingan „Bahor qaytmaydi“ qissasi boʻldi.",
      books:[
        // {
        //   id:31,
        //   bookname:"Pinak",
        //   bookpic:"https://saviya.uz/wp-content/uploads/2017/04/abdulla_avloniy-640x400.jpg?x94708",
        //   ranking:3.3,
        //   commitnum:60,
        //   pages:300,
        //   published:2001,
        //   genre:"drama",
        //   publishing:"nihol nashr",
        // },
        {
          id:31,
          bookname:"the other",
          bookpic: "https://img1.od-cdn.com/ImageType-400/1071-1/E0B/A57/F0/%7BE0BA57F0-58D2-49BF-948D-68CA21FFA214%7DImg400.jpg",
          ranking:4.1,
          commitnum:865,
          author:"Abdulla Qodiriy",
          pages:100,
          published:2001,
          genre:"drama",
          publishing:"nihol nashr",
          moreinfo:"Роман ўтган асрнинг йигирманчи йилларида Германияда таҳсил олган ва собиқ Совет Иттифоқи томонидан шафқатсизларча қатл этилган миллат йигит-қизларининг  хотирасига бағишланади Роман воқеаларини қисқача сўзлар билан ифода этиб бўлмайди. Барчаси шу қадар  тиғизки, шошириб қўяди. Мажоз, образ, ифода, ўт, ҳеч кимникига ўхшамаган лиризмни ҳис қиласиз. Миллият, соф муҳаббат,  кўринмас ва ошкор фожиалар, тарих, бугун ва эртанинг бир-бирига кавшарланган ҳалқаси, ростлик даъвосидаги ёлғонлар, руҳ ва қондаги парадокслар сизни ўтмиш ва келажак куйига асир қилади, ўйлатади, йиғлатади ва аччиқ-аччиқ кулдиради.  Ўтган аср бошида Германияда ўқиган талабалар, улар маслаги ва фожиали қисмати бугунги ёшлар мақсади билан бир тарозига тортилади.",
          paperbook:211,
          audiobook:"3:23",
          elektron:"pdf, epub",
          aboutauthor:"Abdulla Avloniy XIX asr oxiri XX asr boshidagi oʻzbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobidir. U Toshkentning Mergancha mahallasida toʻquvchi Miravlon aka oilasida tavallud topdi. Avval Oʻqchidagi boshlangʻich maktabda, soʻng shahar madrasalaridan birida tahsil oldi. ",
          quote:"Inson bolasi ne kunlarni ko‘rmaydi?!Har bir odam o‘z g‘ami bilan bo‘lsa, hayotdan ko‘z yumib ketganlarga umr bo‘yi motam tutib o‘tsa, bu moddiy olam shu kunlarga yetolarmidi? Hayot to‘lqini ojizlarni qirg‘oqqa irg‘itib tashlaydi. Oqimga qarshi suza olganlar, to‘lqinni egarlaganlargina ertangi kunga yetib keladi.",
          quote2:"Yer kurrasida chumolidek mehnat qilayotganlardan ko‘ra, tuproq tagida yotganlar ko‘p. Yer qatlami odam suyaklariga to‘lib ketgan.",
          rewiev:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
          recommendation:[
            {
              picture:dunyoningishlari,
              title:"Dunyoning ishlari",
              ranking: 2.5,
              comments:200,
            },
            {
              picture:ikkieshikorasi,
              title:"Ikki eshik orasi",
              ranking: 4.3,
              comments:300,
            },
            {
              picture:tushda,
              title:"Tushda kechgan umrlar",
              ranking: 4.5,
              comments:5200,
            },
            {
              picture:sophie,
              title:"To Kill a Mockingbird",
              ranking: 3.9,
              comments:1400,
            },
            {
              picture:littleprince,
              title:"The Little Prince",
              ranking: 4.9,
              comments:300,
            },
            {
              picture:candide,
              title:"Candide",
              ranking: 3.9,
              comments:300,
            },
          ]

        },
      ],
    },
    {
      id:10,
      fname:"Mahmud",
      name:"Mahmudo'ja Behbudiy",
      img:behmudiy,
      wasborn:"5-may 1875",
      died:"7-avg 1919",
      birthAddress:"Toshkent, Uzbekistan",
      desc:`XIX asr oxiri XX asr boshidagi ozbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobi Abdulla Avloniydir. U 1878 yilning 12 iyulida Toshkentning Mergancha mahallasida, toquvchi Miravlon aka oilasida dunyoga keldi. Bolaligi Mirobod mahallifatparvar sifatida tanildi va olkadagi ijgimoiy-madaniy harakatchilikning faol namoyandalaridan biriga aylandi.`,
      worklife:"Yozuvchining ilk asari 1962-yilda „Poʻlat chavandoz“ nomida ocherklar toʻplami tarzida nashrdan chiqdi. Ammo yozuvchiga muvaffaqiyat keltirgan asar 1970-yilda nashr qilingan „Bahor qaytmaydi“ qissasi boʻldi.",
      books:[
        // {
        //   id:32,
        //   bookname:"Pinak",
        //   bookpic:"https://saviya.uz/wp-content/uploads/2017/04/abdulla_avloniy-640x400.jpg?x94708",
        //   ranking:3.3,
        //   commitnum:60,
        //   pages:300,
        //   published:2001,
        //   genre:"drama",
        //   publishing:"nihol nashr",
        // },
        {
          id:32,
          bookname:"Nightenagle",
          bookpic: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1598993363i/21853621.jpg",
          ranking:4.1,
          commitnum:865,
          author:"Mahmudo'ja Behbudiy",
          pages:100,
          published:2001,
          genre:"drama",
          publishing:"nihol nashr",
          moreinfo:"Роман ўтган асрнинг йигирманчи йилларида Германияда таҳсил олган ва собиқ Совет Иттифоқи томонидан шафқатсизларча қатл этилган миллат йигит-қизларининг  хотирасига бағишланади Роман воқеаларини қисқача сўзлар билан ифода этиб бўлмайди. Барчаси шу қадар  тиғизки, шошириб қўяди. Мажоз, образ, ифода, ўт, ҳеч кимникига ўхшамаган лиризмни ҳис қиласиз. Миллият, соф муҳаббат,  кўринмас ва ошкор фожиалар, тарих, бугун ва эртанинг бир-бирига кавшарланган ҳалқаси, ростлик даъвосидаги ёлғонлар, руҳ ва қондаги парадокслар сизни ўтмиш ва келажак куйига асир қилади, ўйлатади, йиғлатади ва аччиқ-аччиқ кулдиради.  Ўтган аср бошида Германияда ўқиган талабалар, улар маслаги ва фожиали қисмати бугунги ёшлар мақсади билан бир тарозига тортилади.",
          paperbook:211,
          audiobook:"3:23",
          elektron:"pdf, epub",
          aboutauthor:"Abdulla Avloniy XIX asr oxiri XX asr boshidagi oʻzbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobidir. U Toshkentning Mergancha mahallasida toʻquvchi Miravlon aka oilasida tavallud topdi. Avval Oʻqchidagi boshlangʻich maktabda, soʻng shahar madrasalaridan birida tahsil oldi. ",
          quote:"Inson bolasi ne kunlarni ko‘rmaydi?!Har bir odam o‘z g‘ami bilan bo‘lsa, hayotdan ko‘z yumib ketganlarga umr bo‘yi motam tutib o‘tsa, bu moddiy olam shu kunlarga yetolarmidi? Hayot to‘lqini ojizlarni qirg‘oqqa irg‘itib tashlaydi. Oqimga qarshi suza olganlar, to‘lqinni egarlaganlargina ertangi kunga yetib keladi.",
          quote2:"Yer kurrasida chumolidek mehnat qilayotganlardan ko‘ra, tuproq tagida yotganlar ko‘p. Yer qatlami odam suyaklariga to‘lib ketgan.",
          rewiev:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
          recommendation:[
            {
              picture:dunyoningishlari,
              title:"Dunyoning ishlari",
              ranking: 2.5,
              comments:200,
            },
            {
              picture:ikkieshikorasi,
              title:"Ikki eshik orasi",
              ranking: 4.3,
              comments:300,
            },
            {
              picture:tushda,
              title:"Tushda kechgan umrlar",
              ranking: 4.5,
              comments:5200,
            },
            {
              picture:sophie,
              title:"To Kill a Mockingbird",
              ranking: 3.9,
              comments:1400,
            },
            {
              picture:littleprince,
              title:"The Little Prince",
              ranking: 4.9,
              comments:300,
            },
            {
              picture:candide,
              title:"Candide",
              ranking: 3.9,
              comments:300,
            },
          ]

        },
      ],
    },
    
    {
      id:11,
      fname:"Hoji",
      name:"Hoji Muin",
      img:hoji,
      wasborn:"5-may 1883",
      died:"7-avg 1942",
      birthAddress:"Toshkent, Uzbekistan",
      desc:`XIX asr oxiri XX asr boshidagi ozbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobi Abdulla Avloniydir. U 1878 yilning 12 iyulida Toshkentning Mergancha mahallasida, toquvchi Miravlon aka oilasida dunyoga keldi. Bolaligi Mirobod mahallifatparvar sifatida tanildi va olkadagi ijgimoiy-madaniy harakatchilikning faol namoyandalaridan biriga aylandi.`,
      worklife:"Yozuvchining ilk asari 1962-yilda „Poʻlat chavandoz“ nomida ocherklar toʻplami tarzida nashrdan chiqdi. Ammo yozuvchiga muvaffaqiyat keltirgan asar 1970-yilda nashr qilingan „Bahor qaytmaydi“ qissasi boʻldi.",
      books:[
        // {
        //   id:33,
        //   bookname:"Pinak",
        //   bookpic:"https://saviya.uz/wp-content/uploads/2017/04/abdulla_avloniy-640x400.jpg?x94708",
        //   ranking:3.3,
        //   commitnum:60,
        //   pages:300,
        //   published:2001,
        //   genre:"drama",
        //   publishing:"nihol nashr",
        // },
        {
          id:33,
          bookname:"Tuscany Marvel",
          bookpic: "https://cdn.shopify.com/s/files/1/2131/2399/products/TuscanyCoverFlatFRONT_1A_af60b5e2-812c-41c9-b614-2bbc8e7e2300_750x750.jpg?v=1630441943",
          ranking:4.1,
          commitnum:865,
          author:"Hoji Muin",
          pages:100,
          published:1992,
          genre:"drama",
          publishing:"nihol nashr",
          moreinfo:"Роман ўтган асрнинг йигирманчи йилларида Германияда таҳсил олган ва собиқ Совет Иттифоқи томонидан шафқатсизларча қатл этилган миллат йигит-қизларининг  хотирасига бағишланади Роман воқеаларини қисқача сўзлар билан ифода этиб бўлмайди. Барчаси шу қадар  тиғизки, шошириб қўяди. Мажоз, образ, ифода, ўт, ҳеч кимникига ўхшамаган лиризмни ҳис қиласиз. Миллият, соф муҳаббат,  кўринмас ва ошкор фожиалар, тарих, бугун ва эртанинг бир-бирига кавшарланган ҳалқаси, ростлик даъвосидаги ёлғонлар, руҳ ва қондаги парадокслар сизни ўтмиш ва келажак куйига асир қилади, ўйлатади, йиғлатади ва аччиқ-аччиқ кулдиради.  Ўтган аср бошида Германияда ўқиган талабалар, улар маслаги ва фожиали қисмати бугунги ёшлар мақсади билан бир тарозига тортилади.",
          paperbook:211,
          audiobook:"3:23",
          elektron:"pdf, epub",
          aboutauthor:"Abdulla Avloniy XIX asr oxiri XX asr boshidagi oʻzbek milliy madaniyatining mashhur vakillaridan biri maʼrifatparvar shoir, dramaturg, jurnalist, olim, davlat va jamoat arbobidir. U Toshkentning Mergancha mahallasida toʻquvchi Miravlon aka oilasida tavallud topdi. Avval Oʻqchidagi boshlangʻich maktabda, soʻng shahar madrasalaridan birida tahsil oldi. ",
          quote:"Inson bolasi ne kunlarni ko‘rmaydi?!Har bir odam o‘z g‘ami bilan bo‘lsa, hayotdan ko‘z yumib ketganlarga umr bo‘yi motam tutib o‘tsa, bu moddiy olam shu kunlarga yetolarmidi? Hayot to‘lqini ojizlarni qirg‘oqqa irg‘itib tashlaydi. Oqimga qarshi suza olganlar, to‘lqinni egarlaganlargina ertangi kunga yetib keladi.",
          quote2:"Yer kurrasida chumolidek mehnat qilayotganlardan ko‘ra, tuproq tagida yotganlar ko‘p. Yer qatlami odam suyaklariga to‘lib ketgan.",
          rewiev:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
          recommendation:[
            {
              picture:dunyoningishlari,
              title:"Dunyoning ishlari",
              ranking: 2.5,
              comments:200,
            },
            {
              picture:ikkieshikorasi,
              title:"Ikki eshik orasi",
              ranking: 4.3,
              comments:300,
            },
            {
              picture:tushda,
              title:"Tushda kechgan umrlar",
              ranking: 4.5,
              comments:5200,
            },
            {
              picture:sophie,
              title:"To Kill a Mockingbird",
              ranking: 3.9,
              comments:1400,
            },
            {
              picture:littleprince,
              title:"The Little Prince",
              ranking: 4.9,
              comments:300,
            },
            {
              picture:candide,
              title:"Candide",
              ranking: 3.9,
              comments:300,
            },
          ]

        },
      ],
    },
  ]

  export {Objects}

  